### ISSUE TITLE
Support for iPhone Xs Max

### ISSUE THREAD

**Issue by arturgrigor** [keygx/TinyToast#5]
The library doesn't properly check if the device has a notch, it only checks if the device has the screen resolution of iPhone X and iPhone Xs but not iPhone Xs Max and because of that, the toast looks weird when shown using the `.top` valign.

**Comment by quockhai** [comment]
Do you run in simulator? Check in real device :)

**Comment by arturgrigor** [comment]
No, I ran it on my device and it shows the toast underneath the notch.

**Comment by keygx** [comment]
I was released Ver.1.3.0.
iPhone Xs Max and XR are supported.
Please give it a try.

**Comment by arturgrigor** [comment]
Looks good now. Thanks! ✌️
